title: Versenyprogramozás
description: Algoritmuselmélet és programozási versenyek.
logo:
google_analytics:

github_link: https://github.com/versenyprogramozas
youtube_link: https://www.youtube.com/@versenyprogramozas
discord_link: https://vprog.hu/discord

theme: jekyll-theme-cayman

markdown: kramdown

plugins:
  - jekyll-redirect-from
