title: Versenyprogramozás
description: Algoritmuselmélet és programozási versenyek.
logo:
google_analytics:

github_link: https://github.com/versenyprogramozas
youtube_link: https://www.youtube.com/channel/UCuL_AjPTt_RkATRRzVNZfAQ
discord_link: https://discord.gg/B2ecH76

theme: jekyll-theme-cayman

markdown: kramdown
