title: Versenyprogramozás
description: Algoritmuselmélet, programozási versenyek (ACM-ICPC, Google Code Jam, ...).
github: https://github.com/versenyprogramozas
youtube: https://www.youtube.com/channel/UCuL_AjPTt_RkATRRzVNZfAQ
discord: https://discord.gg/B2ecH76
theme: jekyll-theme-cayman
