site_name: Versenyprogramozás

plugins:
  - redirects:
      redirect_maps:
        'acm.md': 'https://cs.bme.hu/acm'
        'bme.md': 'https://cs.bme.hu/acm'
        'zoom.md': 'https://us06web.zoom.us/j/86740035264'
        'cf.md': 'https://codeforces.com/group/2cnVva0QXt/join'
        'codeforces.md': 'https://codeforces.com/group/2cnVva0QXt/join'
        'discord.md': 'https://discord.gg/J2ew94XErW'
        'github.md': 'https://github.com/versenyprogramozas'
        'miro.md': 'https://miro.com/welcomeonboard/YjdSWVU4SlNwYW51d2x5NjNvUTg0WU1IWU04THBHQXh0VjZTNERUZlpxc0tDUlNIbVlqNmp0TTFVQkJwcGNaSHwzMDc0NDU3MzQ1NzgwOTgyOTMzfDI=?share_link_id=905786391766'
        'wb.md': 'https://miro.com/welcomeonboard/YjdSWVU4SlNwYW51d2x5NjNvUTg0WU1IWU04THBHQXh0VjZTNERUZlpxc0tDUlNIbVlqNmp0TTFVQkJwcGNaSHwzMDc0NDU3MzQ1NzgwOTgyOTMzfDI=?share_link_id=905786391766'
        'whiteboard.md': 'https://miro.com/welcomeonboard/YjdSWVU4SlNwYW51d2x5NjNvUTg0WU1IWU04THBHQXh0VjZTNERUZlpxc0tDUlNIbVlqNmp0TTFVQkJwcGNaSHwzMDc0NDU3MzQ1NzgwOTgyOTMzfDI=?share_link_id=905786391766'
        'youtube.md': 'https://www.youtube.com/@versenyprogramozas/'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: hu
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Sötét mód
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Világos mód
      primary: teal
      accent: lime
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://vprog.hu/discord
    - icon: fontawesome/brands/github
      link: https://github.com/versenyprogramozas
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@versenyprogramozas

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  Versenyprogramozás